services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

  app:
    image: otasmusic/backend:dev
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    restart: unless-stopped
    volumes:
      # share static content to nginx container
      - static_volume:/usr/src/backend/static
      - ./backend:/usr/src/backend
    depends_on:
      - db
    ports:
      - '${APP_PORT:-8000}:8000'

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app

    # uncomment if needed access from host (browser), otherwise keep commented
    # because clashes with other nginx instances (with port 80)
#    ports:
#      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # provide static data from [app] to [nginx]
      - static_volume:/home/app/static
    labels:
      - "traefik.http.routers.otasmusic.entrypoints=websecure"
      - "traefik.http.routers.otasmusic.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.otasmusic.tls=true"
      - "traefik.http.routers.otasmusic.tls.certresolver=default"

volumes:
  static_volume: