# Generated by Django 2.0.3 on 2018-07-10 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['song__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AuthorMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['song__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BandContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=256)),
                ('order', models.SmallIntegerField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='otasmusic.Band')),
            ],
            options={
                'ordering': ['order', 'contact'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('where', models.CharField(max_length=100)),
                ('event_url', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=1024)),
                ('gig_datetime', models.DateTimeField(blank=True, null=True)),
                ('gig_order', models.SmallIntegerField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.Band')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=256)),
                ('order', models.SmallIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='otasmusic.Person')),
            ],
            options={
                'ordering': ['order', 'contact'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('url', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otasmusic.Band')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='RecordContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.Person')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.Record')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecordContributorSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('record_contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.RecordContributor')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('accoustic-guitar', 'accoustic guitar'), ('bass', 'bass'), ('backing-vocal', 'backing vocal'), ('drums-track', 'drums track'), ('drums', 'drums'), ('electric-guitar', 'electric guitar'), ('keyboard', 'keyboard'), ('keyboard-track', 'keyboard track'), ('lead-vocal', 'lead vocal'), ('mastering', 'mastering'), ('mix', 'mix'), ('recording', 'recording'), ('saxophone', 'saxophone'), ('trombone', 'trombone'), ('trombone', 'video')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='otasmusic.Band')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recordcontributorskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='otasmusic.Skill'),
        ),
        migrations.AddField(
            model_name='record',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='otasmusic.Song'),
        ),
        migrations.AddField(
            model_name='authormusic',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.Person'),
        ),
        migrations.AddField(
            model_name='authormusic',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.Song'),
        ),
        migrations.AddField(
            model_name='authorlyrics',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.Person'),
        ),
        migrations.AddField(
            model_name='authorlyrics',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otasmusic.Song'),
        ),
        migrations.AlterUniqueTogether(
            name='recordcontributorskill',
            unique_together={('record_contributor', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='recordcontributor',
            unique_together={('record', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='authormusic',
            unique_together={('song', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='authorlyrics',
            unique_together={('song', 'person')},
        ),
    ]
