# Generated by Django 2.0.3 on 2018-07-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otasmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('url_img_front', models.CharField(blank=True, max_length=1024, null=True)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='otasmusic.Band')),
            ],
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-release_date', 'album_order']},
        ),
        migrations.AddField(
            model_name='record',
            name='album_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(choices=[('accoustic-guitar', 'accoustic guitar'), ('bass', 'bass'), ('backing-vocal', 'backing vocal'), ('drums-track', 'drums track'), ('drums', 'drums'), ('electric-guitar', 'electric guitar'), ('keyboard', 'keyboard'), ('keyboard-track', 'keyboard track'), ('lead-vocal', 'lead vocal'), ('mastering', 'mastering'), ('mix', 'mix'), ('recording', 'recording'), ('saxophone', 'saxophone'), ('trombone', 'trombone'), ('video', 'video'), ('metallophone', 'metallophone')], unique=True),
        ),
        migrations.AddField(
            model_name='record',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otasmusic.Album'),
        ),
    ]
