# Generated by Django 2.0.3 on 2018-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otasmusic', '0002_auto_20180719_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordcontributorskill',
            options={'ordering': ['skill__order']},
        ),
        migrations.RemoveField(
            model_name='recordcontributorskill',
            name='order',
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
