# Generated by Django 2.0.3 on 2018-07-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otasmusic', '0003_auto_20180728_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='created_by',
        ),
    ]
