# Generated by Django 2.0.3 on 2018-07-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otasmusic', '0004_auto_20180728_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
    ]
