# Generated by Django 2.2.1 on 2020-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otasmusic', '0006_auto_20190929_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(choices=[('accoustic-guitar', 'accoustic guitar'), ('bass', 'bass'), ('backing-vocal', 'backing vocal'), ('camera', 'camera'), ('drums-track', 'drums track'), ('drums', 'drums'), ('electric-guitar', 'electric guitar'), ('keyboard', 'keyboard'), ('keyboard-track', 'keyboard track'), ('lead-vocal', 'lead vocal'), ('mastering', 'mastering'), ('metallophone', 'metallophone'), ('mix', 'mix'), ('mouth-organ', 'mouth organ'), ('recording', 'recording'), ('saxophone', 'saxophone'), ('trombone', 'trombone'), ('video', 'video')], unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
